name: Sotabosc
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: building-app
        uses: actions/checkout@v3
      - name: Introduction
        run: echo "🔎 Building app"
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build -c=production
  finish:
    runs-on: ubuntu-latest
    needs:
      - build
    if: success()
    steps:
      - name: Finish process
        run: echo "🎉 Deployed with success"
